insert into public.posts (
  slug,
  title,
  subtitle,
  excerpt,
  body_markdown,
  category,
  status,
  hero_image_url,
  caption,
  author_name,
  published_at,
  featured,
  featured_rank
) values
(
  'waiting-face-film',
  '나는 복음을 설명하기보다 기다림의 얼굴을 찍고 싶었다',
  '독립영화 감독 한서진 인터뷰',
  '신앙, 실패, 제작비, 교회와 영화의 거리, 그리고 창작자의 소명에 대해 나눈 긴 대화.',
  '한서진 감독은 영화가 정답을 말하는 장르라고 생각하지 않는다. 그에게 영화는 오래 바라보는 일이고, 쉽게 판단하지 않기 위해 카메라를 낮추는 일이다.\n\n이번 인터뷰에서 그는 기독교 창작자가 작품 속에 신앙을 넣는 방식보다, 세계를 바라보는 태도가 먼저 바뀌어야 한다고 말했다.',
  'film',
  'published',
  'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1600&q=80',
  '늦은 밤 촬영 현장. 그는 인물의 침묵을 가장 오래 기다리는 순간이라고 말했다.',
  '둘레살롱 편집부',
  '2026-05-24T00:00:00+09:00',
  true,
  1
),
(
  'songs-outside-worship',
  '예배음악 밖에서 만난 신앙의 노래',
  '음악가 이다니엘과의 짧은 대화',
  '찬양의 형식 밖에서도 기도처럼 들리는 사운드와 가사를 이야기했다.',
  '이다니엘 프로듀서는 예배음악과 대중음악을 엄격히 나누는 방식보다, 소리가 사람을 어떻게 기다리게 하는지에 관심이 있다.',
  'music',
  'published',
  'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1600&q=80',
  '녹음실의 조용한 오후. 그는 여백을 가장 중요한 악기라고 불렀다.',
  '둘레살롱 편집부',
  '2026-05-21T00:00:00+09:00',
  false,
  3
),
(
  'gallery-five-this-week',
  '이번 주 볼 만한 전시 5개',
  '서울의 작은 갤러리에서 만나는 회복의 장면',
  '작업실의 재료, 지역의 기억, 공동체의 질문을 다루는 전시를 골랐다.',
  '이번 주 전시는 큰 미술관보다 작은 공간에서 오래 머무를 만한 작업을 중심으로 골랐다.',
  'art',
  'published',
  'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1600&q=80',
  '작은 전시 공간은 작품과 관람자의 속도를 천천히 맞춘다.',
  '둘레살롱 편집부',
  '2026-05-22T00:00:00+09:00',
  false,
  2
),
(
  'books-for-makers',
  '창작자에게 권하는 신앙과 예술의 책 5권',
  '이번 달 문화 리딩 키트',
  '창작자의 소명, 노동, 실패, 상상력을 함께 읽을 수 있는 책을 골랐다.',
  '창작자는 자기 안의 질문만으로 오래 버티기 어렵다. 좋은 책은 작업의 언어를 넓히고, 실패를 혼자 감당하지 않게 만든다.',
  'books',
  'published',
  'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1600&q=80',
  '읽기는 창작자의 작업실을 조용히 넓히는 일이다.',
  '조민우',
  '2026-05-20T00:00:00+09:00',
  false,
  4
)
on conflict (slug) do nothing;
